#!/usr/bin/env bash
# Script displays "Best School" 10 times but on the 9 iteration it will display "Best school" and "Hi"

i=0
while [ $i -lt 10 ]; do
    if [ $i -eq 8 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    ((i++))
done
