#!/usr/bin/env bash
#Script displays time for 12hour 59minutes

hour=0

while [ $hour -le 12 ]; do
    echo "Hour: $hour"

    min=1
    while [ $min -le 59 ]; do
        echo "$min"
        ((min++))
    done
    ((hour++))

done