#!/usr/bin/env bash 

# Installing UFW

sudo apt update
sudo apt install ufw

# blocking incoming traffic allowing outgoing

sudo ufw defualt deny incoming
sudo ufw defualt allow outgoing

# Configuring UFW

sudo ufw allow ssh
sudo ufw allow https
sudo ufw allow http

sudo ufw enable
sudo ufw status
